#!/bin/sh
# Tunables:
RATE="10M"

############################################################################
ZFS_LIST=$(env LC_ALL=C zfs list -H -t filesystem \
    -o mountpoint,xyz.haasn:force-cache | shuf)

TARGETS_DATA=$(echo "$ZFS_LIST" | awk -F '\t' \
    'tolower($1) !~ /none/ && tolower($2) ~ /true/ {print $1}')

TARGETS_META=$(echo "$ZFS_LIST" | awk -F '\t' \
    'tolower($1) !~ /none/ && tolower($2) ~ /metadata/ {print $1}')

for t in $TARGETS_DATA
do
    echo Forcing ${t} into data cache
    /bin/tar cf - --one-file-system "$t" 2>/dev/null | pv -q -L "$RATE" >/dev/null
done

for t in $TARGETS_META
do
    echo Forcing ${t} into metadata cache
    /usr/bin/find "$t" -xdev >/dev/null 2>&1
done
