" custom keybindings
noremap j gj
noremap k gk

" easier buffer navigation
map <Esc>h <C-w>h
map <Esc>j <C-w>j
map <Esc>k <C-w>k
map <Esc>l <C-w>l
map <Esc>H <C-w>H
map <Esc>J <C-w>J
map <Esc>K <C-w>K
map <Esc>L <C-w>L

" fix bold colors
set term=rxvt-unicode

set hlsearch
set is

syntax sync fromstart
syntax on

set background=dark
set showcmd
set showmatch
set ignorecase
set smartcase
set nojoinspaces
set scrolloff=3
set timeoutlen=0
set modeline
set autochdir

set expandtab
set shiftwidth=4
set softtabstop=4

" code folding
set foldmethod=syntax
set foldnestmax=1
set foldlevel=0

" ctags
noremap <C-d> <C-]>
set tags=tags;
"let g:easytags_auto_highlight = 0
"let g:easytags_dynamic_files = 2
"let g:easytags_always_enabled = 1
"let g:easytags_async = 1

set cc=81
set foldcolumn=1
set foldopen=block,hor,mark,percent,quickfix,search,tag,undo
set number
set numberwidth=1

set completeopt=menu,menuone,longest,preview

" the default was just horrid
colorscheme peachpuff

highlight Identifier ctermfg=53
highlight Pmenu ctermbg=16 ctermfg=79
highlight PmenuSel ctermbg=49 ctermfg=79
highlight ErrorMsg ctermbg=32 ctermfg=79
highlight Search ctermbg=none ctermfg=29
highlight MatchParen ctermbg=none ctermfg=31
highlight ColorColumn ctermbg=80
highlight SpellBad ctermfg=1 ctermbg=none
highlight SpellCap ctermfg=none ctermbg=none
highlight SpellRare ctermfg=none ctermbg=none
highlight SpellLocal ctermfg=3 ctermbg=none
highlight mailURL ctermfg=2
highlight mailEmail ctermfg=5
highlight Folded ctermfg=7  ctermbg=80
highlight FoldColumn ctermfg=82 ctermbg=16
highlight LineNr ctermfg=81 ctermbg=16
highlight link Member Normal
highlight link EnumeratorName EnumerationName
highlight link EnumerationName Type
highlight EnumerationValue ctermfg=41
highlight DefinedName ctermfg=70
highlight StatusLineNC cterm=none ctermfg=14 ctermbg=80
highlight StatusLine cterm=bold ctermfg=15 ctermbg=80

" match extra whitespace
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+$\| \+\ze\t/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/

" custom aliases
command Reply :%s/^\t/> /g

command -bang -bar Quit q<bang>
command -bang -bar -nargs=? -complete=file -range=% Write <line1>,<line2>w<bang> <args>

set autoindent
set backspace=indent

execute pathogen#infect()
filetype plugin indent on

" auto-load correct highlighting highlighting
au BufNewFile,BufRead *.frag,*.vert,*.fp,*.vp,*.glsl setf glsl
au BufNewFile,BufRead *.vpy setf python
